### PR TITLE
Belarusian translation (100% coverage)

### PR DESCRIPTION
**Pull request by skepsys**
Belarusian (be_BY) translation, made based on files from `/app/src/main/res/values-ru/`, 100% coverage.
As discussed previously in #703 , all changes were placed in a new folder `/app/src/main/res/values-be/`.

Formatting may be different from the sources, since the output files were autogenerated by Crowdin.
See the translation project at [https://crowdin.com/project/stepik-android-be](https://crowdin.com/project/stepik-android-be)

Please also check if any additional configuration should be made.

### CODE REVIEW

**Comment by eadm** [comment]
With latest release we've added a couple of new strings. Can you add them to your translation, please?

**Comment by skepsys** [comment]
> With latest release we've added a couple of new strings. Can you add them to your translation, please?

Sure. 26 new lines (peer review feature) has been translated. Pull request updated.

**Comment by skepsys** [comment]
Oops, now the pull request contains changes from `upstream/master` not being merged into `upstream/development` yet. I guess you should update your `development` branch with `master` before merging this PR.

**Review by eadm — APPROVED** [review]

**Comment by skepsys** [comment]
@eadm thanks for merging. Would you please provide at least approximate dates when the translation could be available on Google Play?

**Comment by eadm** [comment]
We are going to start rollout on 23.11.2020

**Pull request merged**
